//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public Accessory()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int AccessID { get; set; }
        public string AccessName { get; set; }
        public string AccessStyle { get; set; }
        public string AccessColor { get; set; }
        public string AccessType { get; set; }
        public string AccessImage { get; set; }
        public string AccessSeason { get; set; }
        public string AccessOccasion { get; set; }
    
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
